
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '7DBA7867E2D7567A3B20D55D5373384F'
    
_lr_action_items = {'LETTER':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,],[-1,-4,3,-1,-9,-8,-1,-2,-6,-5,3,-7,-10,-1,-3,]),'$end':([0,1,2,3,4,5,7,8,11,13,14,],[-1,-4,0,-1,-9,-8,-2,-6,-7,-1,-3,]),'RBR':([3,6,7,8,9,10,11,12,],[-1,-1,-2,-6,-5,13,-7,-10,]),'LBR':([0,1,2,3,4,5,7,8,11,13,14,],[-1,-4,6,-1,-9,-8,-2,-6,-7,-1,-3,]),'NUMBER':([3,7,8,11,13,14,],[-1,-2,11,-7,-1,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,3,6,13,],[1,7,9,7,]),'jump':([3,13,],[8,14,]),'substring':([6,],[10,]),'level':([2,],[5,]),'symbol':([2,10,],[4,12,]),'string':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> string","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',32),
  ('jump -> empty','jump',1,'p_jump_empty','parser.py',64),
  ('level -> LBR substring RBR jump','level',4,'p_level_LBR_substring_RBR_jump','parser.py',64),
  ('string -> empty','string',1,'p_string_empty','parser.py',64),
  ('substring -> empty','substring',1,'p_substring_empty','parser.py',64),
  ('symbol -> LETTER jump','symbol',2,'p_symbol_LETTER_jump','parser.py',64),
  ('jump -> jump NUMBER','jump',2,'p_jump_jump_NUMBER','parser.py',73),
  ('string -> string level','string',2,'p_string_string_level','parser.py',73),
  ('string -> string symbol','string',2,'p_string_string_symbol','parser.py',73),
  ('substring -> substring symbol','substring',2,'p_substring_substring_symbol','parser.py',73),
]
